apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: force-pull-cp4i
  namespace: cp4i
spec:
  selector:
    matchLabels:
      name: force-pull-cp4i
  template:
    metadata:
      labels:
        name: force-pull-cp4i
    spec:
      containers:
      - name: force-pull-minimal-build
        imagePullPolicy: Always
        image: image-registry.openshift-image-registry.svc.cluster.local:5000/default/ace-minimal-build:12.0.10.0-alpine
        command: ["sleep"]
        args: ["1000000"]
      imagePullSecrets:
      - name: 'regcred'
